# Generated by Django 2.0.2 on 2018-02-07 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nota',
            name='activa',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='nota',
            name='nombre',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
