# Generated by Django 2.0.2 on 2018-02-08 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20180207_2336'),
    ]

    operations = [
        migrations.AddField(
            model_name='nota',
            name='html',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
