# Generated by Django 2.0.2 on 2018-02-23 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_nota_html'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nota',
            name='html',
        ),
    ]
