# Generated by Django 2.0.2 on 2018-03-19 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_remove_nota_html'),
    ]

    operations = [
        migrations.CreateModel(
            name='LibroNotaAdjunto',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('web.libro',),
        ),
    ]
