# Generated by Django 2.0.2 on 2018-09-16 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_libronotaadjunto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nota',
            old_name='texto',
            new_name='texto_html',
        ),
    ]
