# Generated by Django 2.0.2 on 2018-09-17 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_libronotaadjunto'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='propiedades',
            field=models.TextField(blank=True, null=True, verbose_name='propiedades'),
        ),
    ]
