# Generated by Django 2.0.2 on 2018-09-26 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_user_editor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='editor',
            field=models.CharField(choices=[('summernote', 'Summernote'), ('ckeditor', 'Ckeditor'), ('froala', 'Froala')], default='summernote', max_length=30, verbose_name='editor'),
        ),
    ]
