# Generated by Django 3.0.5 on 2020-04-12 17:40

from django.db import migrations, models
import web.models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_auto_20181002_2314'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdjuntoTemporal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid_id', models.UUIDField()),
                ('fichero', models.FileField(upload_to=web.models.adjunto_upload_to)),
                ('nombre', models.CharField(max_length=200)),
            ],
        ),
    ]
