# Generated by Django 3.1.2 on 2020-10-18 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0011_auto_20201017_0004'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adjuntotemporal',
            options={'verbose_name_plural': 'AdjuntosTemporal'},
        ),
    ]
