# Generated by Django 3.1.2 on 2022-10-08 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0013_auto_20221007_1743'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nota',
            old_name='activa',
            new_name='activo',
        ),
        migrations.RenameField(
            model_name='nota',
            old_name='privada',
            new_name='privado',
        ),
    ]
