# Generated by Django 3.1.2 on 2022-10-10 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0016_agendaevento_aviso_email'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AgendaEventoPrdefinido',
            new_name='AgendaEventoPredefinido',
        ),
    ]
