# Generated by Django 3.1.2 on 2022-10-10 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0017_auto_20221010_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendaevento',
            name='titulo',
            field=models.CharField(max_length=250, verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='agendaeventopredefinido',
            name='titulo',
            field=models.CharField(max_length=250, verbose_name='Título'),
        ),
    ]
