# Generated by Django 4.1.2 on 2022-10-16 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0019_agendaevento_email_enviado_alter_adjunto_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='fcm_token',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
