# Generated by Django 4.1.2 on 2022-10-16 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0020_user_fcm_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendaevento',
            name='aviso_movil',
            field=models.BooleanField(default=False, verbose_name='Avisar con movil'),
        ),
    ]
