# Generated by Django 4.1.2 on 2022-10-16 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0021_agendaevento_aviso_movil'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendaevento',
            name='movil_enviado',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Móvil enviado'),
        ),
        migrations.AlterField(
            model_name='agendaevento',
            name='aviso_movil',
            field=models.BooleanField(default=False, verbose_name='Avisar con móvil'),
        ),
    ]
