# Generated by Django 4.1.2 on 2022-10-28 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0022_agendaevento_movil_enviado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendaevento',
            name='fin',
            field=models.DateTimeField(db_index=True, verbose_name='Fin evento'),
        ),
        migrations.AlterField(
            model_name='agendaevento',
            name='inicio',
            field=models.DateTimeField(db_index=True, verbose_name='Inicio evento'),
        ),
    ]
